<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Infin8.Coapp.BusinessLogic\Infin8.Coapp.BusinessLogic.csproj" />
    <ProjectReference Include="..\Infin8.Coapp.Dto\Infin8.Coapp.Dto.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.ReportViewer.NETCore">
      <HintPath>bin\Debug\net9.0\Microsoft.ReportViewer.NETCore.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
