//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Infin8.Coapp.Models
{
    public partial class Account_Transactions
    {
        [Key]
        public int Acc_Id { get; set; }
        public string Acc_Name { get; set; }
        public string Acc_Type { get; set; }
        public string Acc_Status { get; set; }
        public string Acc_BelongsTo { get; set; }
        public bool Acc_Delete { get; set; }
        public string Component_Name { get; set; }
    }
}
