using System.ComponentModel.DataAnnotations;
namespace Infin8.Coapp.Models
{
    using System;

    public partial class Mem_Demand
    {
        [Key]
        public int MemDemand_Id { get; set; }
        public int Demand_Id { get; set; }
        public Nullable<System.DateTime> DemandCalculatedDate { get; set; }
        public Nullable<System.DateTime> RecoveryDate { get; set; }
        public string? DemandType { get; set; }
        public int Mem_Id { get; set; }
        public int Loan_Id { get; set; }
        public double PIArrearDemand { get; set; }
        public double IntArrearDemand { get; set; }
        public double PrlArrearDemand { get; set; }
        public double PICurrentDemand { get; set; }
        public double IntCurrentDemand { get; set; }
        public double PrlCurrentDemand { get; set; }
        public double PITotalDemand { get; set; }
        public double IntTotalDemand { get; set; }
        public double PrlTotalDemand { get; set; }
        public double Prl_Sched { get; set; }
        public double NonODPrl { get; set; }
        public int DM_Id { get; set; }
        public double ArrearDepositAmount { get; set; }
        public double CurrentDepositAmount { get; set; }
        public double TotalDepositAmount { get; set; }
        public double ArrearPIOnDeposit { get; set; }
        public double CurrentPIOnDeposit { get; set; }
        public double TotalPIOnDeposit { get; set; }
        public int SuspenseLed_Id { get; set; }
        public double ArrearSuspenseAmount { get; set; }
        public double CurrentSuspenseAmount { get; set; }
        public double TotalSuspenseAmount { get; set; }
        public double TotalDemandAmount { get; set; }
        public double PIArrearCollection { get; set; }
        public double IntArrearCollection { get; set; }
        public double PrlArrearCollection { get; set; }
        public double PICurrentCollection { get; set; }
        public double IntCurrentCollection { get; set; }
        public double PrlCurrentCollection { get; set; }
        public double PITotalCollection { get; set; }
        public double IntTotalCollection { get; set; }
        public double PrlTotalCollection { get; set; }
        public double ArrearDepositCollection { get; set; }
        public double CurrentDepositCollection { get; set; }
        public double TotalDepositCollection { get; set; }
        public double ArrearPIOnDepositCollection { get; set; }
        public double CurrentPIOnDepositCollection { get; set; }
        public double TotalPIOnDepositCollection { get; set; }
        public double ArrearSuspenseCollection { get; set; }
        public double CurrentSuspenseCollection { get; set; }
        public double TotalSuspenseCollection { get; set; }
        public double TotalCollectionAmount { get; set; }
        public int SuspenseDueByLed_Id { get; set; }
        public double TotalDueByCollection { get; set; }
        public int Voc_Id { get; set; }
        public int Usr_Id { get; set; }
        public int Yr_Id { get; set; }
        public double LoanOS { get; set; }
        public double PenalInterestCalculatedAmount { get; set; }
        public double InterestCalculatedAmount { get; set; }
        public bool MemDemand_Delete { get; set; }
        public bool StopDemand { get; set; }
        public double Prl_SchedForStopDemand { get; set; }
        public int IntCalcForStopDemand { get; set; }
        public bool IsAppropriated { get; set; }
        public bool IsRecoverySaved { get; set; }
        public string? PerNo { get; set; }
        public string? PerName { get; set; }
        public int Recovery_Id { get; set; }
        public double PIArrearDemand2 { get; set; }
        public double IntArrearDemand2 { get; set; }
        public double PrlArrearDemand2 { get; set; }
        public double PICurrentDemand2 { get; set; }
        public double IntCurrentDemand2 { get; set; }
        public double PrlCurrentDemand2 { get; set; }
        public double PITotalDemand2 { get; set; }
        public double IntTotalDemand2 { get; set; }
        public double PrlTotalDemand2 { get; set; }
        public double ArrearDepositAmount2 { get; set; }
        public double CurrentDepositAmount2 { get; set; }
        public double TotalDepositAmount2 { get; set; }
        public double ArrearPIOnDeposit2 { get; set; }
        public double CurrentPIOnDeposit2 { get; set; }
        public double TotalPIOnDeposit2 { get; set; }
        public double ArrearSuspenseAmount2 { get; set; }
        public double CurrentSuspenseAmount2 { get; set; }
        public double TotalSuspenseAmount2 { get; set; }
        public double TotalDemandAmount2 { get; set; }
        public int TD_Id { get; set; }
        public int RDInstalmentAmount { get; set; }
        public int RDNoOfInstalments { get; set; }
        public int RDDemandAmount { get; set; }
        public int PIOnRDArrearAmount { get; set; }
        public int PIOnRDCalcAmount { get; set; }
        public int PIOnRDTotalAmount { get; set; }
        public Nullable<System.DateTime> PIOnRDApplicationDate { get; set; }
        public int RDTotalDemandAmount { get; set; }
        public int RDReceiptAmount { get; set; }
        public int PIOnRDReceiptAmount { get; set; }
        public int RDTotalReceiptAmount { get; set; }
        public int RDNoOfInstalments2 { get; set; }
        public int RDDemandAmount2 { get; set; }
        public int PIOnRDArrearAmount2 { get; set; }
        public int PIOnRDCalcAmount2 { get; set; }
        public int PIOnRDTotalAmount2 { get; set; }
        public Nullable<System.DateTime> PIOnRDApplicationDate2 { get; set; }
        public int RDTotalDemandAmount2 { get; set; }
        public int RDReceiptAmount2 { get; set; }
        public int PIOnRDReceiptAmount2 { get; set; }
        public int RestrictedDemand { get; set; }
        public int TotalDemand { get; set; }
        public int TotalLoanArrearDemand { get; set; }
        public int TotalLoanCurrentDemand { get; set; }
        public int TotalRDDemand { get; set; }
        public int TotalDepositDemand { get; set; }
        public int DueByDemandLed_Id { get; set; }
        public int ArrearDueByDemandAmount { get; set; }
        public int CurrentDueByDemandAmount { get; set; }
        public int TotalDueByDemandAmount { get; set; }
        public int ArrearDueByCollectionOnDemand { get; set; }
        public int CurrentDueByCollectionOnDemand { get; set; }
        public int TotalDueByCollectionOnDemand { get; set; }
        public int ReferId { get; set; }
        public string? BrCode { get; set; }
        public string? Voc_Status { get; set; }
    }
}
